### ISSUE TITLE
Flashlight feature?

### ISSUE THREAD

**Issue by cnnradams** [AstechzGO/Luminescent#101]
you have a flashlight coming out and everything else gets darker

**Comment by ryanlarkin** [comment]
Maybe for next update, but I want to finish what we've already decided on.

**Comment by cnnradams** [comment]
I think entity needs to be a class not an interface

**Comment by cnnradams** [comment]
like polygonal needs to extend entity

**Comment by cnnradams** [comment]
polygonalentity*

**Comment by cnnradams** [comment]
and then we manually import the render

**Comment by ryanlarkin** [comment]
Why?

**Comment by ryanlarkin** [comment]
Ok sure

**Comment by cnnradams** [comment]
Entity will be a big class

**Comment by ryanlarkin** [comment]
I'll look into it.

**Comment by ryanlarkin** [comment]
> I think entity needs to be a class not an interface

Then why did you close #102?

**Comment by ryanlarkin** [comment]
Sorry for spamming you with emails, but for the flashlight effect, do you think a GLSL shader would work?

**Comment by cnnradams** [comment]
idk

**Comment by cnnradams** [comment]
and I dont mind getting spammed

**Comment by cnnradams** [comment]
did you see the room thing

**Comment by cnnradams** [comment]
it worked :D

**Comment by ryanlarkin** [comment]
The room thing?

**Comment by ryanlarkin** [comment]
Like working?

**Comment by cnnradams** [comment]
yeah

**Comment by cnnradams** [comment]
just had to do some stuff and make bx and by declared inside the for loop

**Comment by cnnradams** [comment]
I overcomplicated it before

**Comment by ryanlarkin** [comment]
Ok, can you push it to a new branch on **your fork**?

**Comment by cnnradams** [comment]
too late .-.

**Comment by ryanlarkin** [comment]
Can you do it though?

**Comment by cnnradams** [comment]
its already on major-update .-.

**Comment by ryanlarkin** [comment]
Still, can you just push it to a new branch on your fork, and I'll fix everything on upstream.

**Comment by cnnradams** [comment]
...

**Comment by cnnradams** [comment]
fine.

**Comment by ryanlarkin** [comment]
And do the same for your entities thing.  I'll delete them after.

**Comment by ryanlarkin** [comment]
And just tell me when you're done.

**Comment by cnnradams** [comment]
ill do it at robotics

**Comment by ryanlarkin** [comment]
ok

**Comment by ryanlarkin** [comment]
Completed by #135
