### ISSUE TITLE
Entity needs to be an extension not an interface

### ISSUE THREAD

**Issue by cnnradams** [AstechzGO/Luminescent#102]

**Comment by ryanlarkin** [comment]
I'm not sure why you closed this. Reopening.

**Comment by ryanlarkin** [comment]
Also, we could do this for the current update, but I think that entity should implement some sort of GameObject.

**Comment by ryanlarkin** [comment]
If understand what you're trying to explain, then I think you could keep entity an interface, but create a Mob class instead that has that stuff.

**Comment by cnnradams** [comment]
Wed then have to create like polygonalmop, rectangular mob, etc and that is not good code

**Comment by ryanlarkin** [comment]
What about something like:

```
public class FooBar extends AnyTypeOfEntity implements LivingEntity
```

That would be easy to change, and would mean just one new class.

**Comment by cnnradams** [comment]
Could work but that means we have to reimplement ai and health etc every enemy

**Comment by ryanlarkin** [comment]
But wouldn't you anyway?

**Comment by cnnradams** [comment]
Not if you extend something which has everything

**Comment by cnnradams** [comment]
Like extend livingentity

**Comment by ryanlarkin** [comment]
But I don't think it would be that hard to do.

**Comment by ryanlarkin** [comment]
You can't extend two things

**Comment by cnnradams** [comment]
Living entity extends entity?

**Comment by ryanlarkin** [comment]
No, living entity is an interface

**Comment by cnnradams** [comment]
like player extends livingentity
and living entity extends entity

**Comment by ryanlarkin** [comment]
Player extends CircularGameObject, and implements LivingEntity,
and living entity extends entity.

**Comment by cnnradams** [comment]
that doesnt work

**Comment by cnnradams** [comment]
you cant extend an interface

**Comment by cnnradams** [comment]
and like I said above that means well be copying and pasting code

**Comment by ryanlarkin** [comment]
I pushed what I was thinking of to entity-interface branch on [my fork](https://github.com/eandr127/Luminescent/tree/entiy-interface).

**Comment by cnnradams** [comment]
well I cant see your fork

**Comment by cnnradams** [comment]
you see the problem thats why we need branches

**Comment by ryanlarkin** [comment]
[https://github.com/eandr127/Luminescent/commit/68e7c9f9761979c24dcbb4363750633f2ae4a5f9](https://github.com/eandr127/Luminescent/commit/68e7c9f9761979c24dcbb4363750633f2ae4a5f9)

**Comment by ryanlarkin** [comment]
Can you see that?

**Comment by cnnradams** [comment]
see but now we have to make sethealth gethealth isdead etc etc in each class with a living entity

**Comment by ryanlarkin** [comment]
In your pull request, you had to do that anyway.  It's different for different entities.  Also, you may have a monster class that does this, then every type of monster already inherits it.

**Comment by cnnradams** [comment]
gethealth should always be the same

**Comment by ryanlarkin** [comment]
I see your point.  Do you have any ideas that could use this living entity thing.

**Comment by cnnradams** [comment]
I say we put all of the different types of entity aka circular rectangular into just entity

**Comment by cnnradams** [comment]
and then livingentity extends entity

**Comment by cnnradams** [comment]
which has health etc

**Comment by cnnradams** [comment]
and then the player extends livingentity and puts in constructor for all 3

**Comment by ryanlarkin** [comment]
But how would you separate the different types of gameobject?

**Comment by cnnradams** [comment]
different constructors in entity

**Comment by cnnradams** [comment]
or methods

**Comment by ryanlarkin** [comment]
I like the idea of different constructors

**Comment by ryanlarkin** [comment]
But what if they have similar parameters?

**Comment by cnnradams** [comment]
if they have the same parameters make it one constructor and we let them choose what to create with an int

**Comment by ryanlarkin** [comment]
Wait, but if you use a single constructor, you can't extend RederableXObject.

**Comment by ryanlarkin** [comment]
Unless you make like a unified renderable thing which takes the argument

**Comment by ryanlarkin** [comment]
I'll show you what I'm thinking.

**Comment by cnnradams** [comment]
literally like in the constructor add "public Entity(int x, int y, int width, int height, int type) {
if(type == 0) {
create rectangle
} else {
create polygon
}
}

**Comment by ryanlarkin** [comment]
But again, it doesn't actually extend the renderer

**Comment by cnnradams** [comment]
you just create one like Renderer r = new Renderer

**Comment by ryanlarkin** [comment]
But you don't get access to stuff like you would if you did:

```
super.x
super.y
```

These aren't designed to be used publicly so it would be bad to add wrapper methods.

**Comment by cnnradams** [comment]
make them public

**Comment by ryanlarkin** [comment]
> These aren't designed to be used publicly so it would be bad to add wrapper methods.

Public is even worse than set and get/methods.

**Comment by cnnradams** [comment]
or make a set and get

**Comment by ryanlarkin** [comment]
That's what I meant by wrapper methods

**Comment by cnnradams** [comment]
well thats the best way to do it

**Comment by ryanlarkin** [comment]
I don't think that there is really a perfect solution to this problem. I'd rather write a little bit of redundant code, than rewrite a ton of wrapper.  Also, it seems wrong for a circle entity to not an extension of a circle object. 

Unless we can come up with a resolution now, I think we should  push this to the next major update.

**Comment by cnnradams** [comment]
Were not gonna do big entity stuff till next update

**Comment by ryanlarkin** [comment]
If you look at the release plan #74, you'll see what's planned.  You can add more stuff if  you want, and I'll just confirm it.  You can do the same for me in the future too.

**Comment by cnnradams** [comment]
so the only thing left is a menu?

**Comment by ryanlarkin** [comment]
And gradle, again, you can request to add stuff to it

**Comment by ryanlarkin** [comment]
If you think my entity thing is acceptable, I can merge it into my branch, then merge the larger pull request. If not, we can discuss it next update.
https://github.com/eandr127/Luminescent/pull/1

**Comment by ryanlarkin** [comment]
> If you think my entity thing is acceptable, I can merge it into my branch, then merge the larger pull request. If not, we can discuss it next update.
> eandr127#1

@stealth2994, what do you think about that?

**Comment by ryanlarkin** [comment]
Completed by #115
