### ISSUE TITLE
Summer Project? (see comment)

### ISSUE THREAD

**Issue by MatEdwards** [AstechzGO/Luminescent#112]
During the meeting today (April 4) we discussed having a summer project, and luminescent was mentioned, I would be willing to help out with the luminescent game as a kind of re-introductory program to java. (i have completely forgotten lots of java specific stuff and terms). Any thoughts?

**Comment by MatEdwards** [comment]
_tear_ I cant label this issue

**Comment by ryanlarkin** [comment]
What should it be labeled?

**Comment by ryanlarkin** [comment]
The only thing that I would have against this, is depending on who you are thinking of having work on this project, it may be too confusing/advanced.  It should be OK if only working on stuff like storyline or having enemies and stuff.

**Comment by ryanlarkin** [comment]
I also would prefer to finish this release first, but all contributions are still welcomed.

**Comment by ryanlarkin** [comment]
Also, if you have extra time, can you find things in the code that should be simplified (or made into objects)?

**Comment by cnnradams** [comment]
Believe me this is not good for introductory, unless we make a really good
back end and just let them deal with the on screen things

**Comment by MatEdwards** [comment]
I was thinking of this more for me....

**Comment by cnnradams** [comment]
OK then sure :) just don't expect it to be user friendly

**Comment by MatEdwards** [comment]
OK, but maybe I could get like one robotics meeting with you or Ryan to get familiarised with the code, because i know there are no comments, and have a bit of a refresher of java vs. C++.

**Comment by ryanlarkin** [comment]
> Believe me this is not good for introductory, unless we make a really good
> back end and just let them deal with the on screen things

Don't we already do that?

**Comment by ryanlarkin** [comment]
@MatEdwards, yeah, I can help you.

**Comment by ryanlarkin** [comment]
Closing dead issue.
