### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by ghost** [AstechzGO/Luminescent#12]
When you set the initial value of fullscreen in the setDisplayMode() function to false the window starts at a different size than what it would be if you started fullscreen, then toggled it with f11

**Comment by eandr127** [comment]
Fixed it simultaneously (#13)

**Comment by ryanlarkin** [comment]
When you were starting in non-fullscreen did you use "setDisplayMode(800, 480, false);"?

**Comment by ryanlarkin** [comment]
Fixed as of #32
