### ISSUE TITLE
ChatRoom

### ISSUE THREAD

**Issue by Patadorea** [AstechzGO/Luminescent#14]
For Outside conversation

**Comment by eandr127** [comment]
Hello

**Comment by Patadorea** [comment]
YEAH

**Comment by Patadorea** [comment]
PARTY

**Comment by eandr127** [comment]
Two is not a party!

**Comment by Patadorea** [comment]
YES IT IS

**Comment by eandr127** [comment]
No

**Comment by Patadorea** [comment]
: 3

**Comment by Patadorea** [comment]
Yes

**Comment by Patadorea** [comment]
Yes

**Comment by eandr127** [comment]
This is a duplicate issue!

**Comment by Patadorea** [comment]
Wut?

**Comment by eandr127** [comment]
Closing

**Comment by Patadorea** [comment]
Why are we sitting next to each other?

**Comment by eandr127** [comment]
This is filling up my spam in my email

**Comment by Patadorea** [comment]
And not talking

**Comment by Patadorea** [comment]
I am the spam overlord

**Comment by eandr127** [comment]
Are  you sure

**Comment by Patadorea** [comment]
Yush

**Comment by D3ZOMBKEELA** [comment]
Please stop. My e-mail is lighting up

**Comment by Patadorea** [comment]
Sorry

**Comment by MatEdwards** [comment]
E-Mail = or > fireworks

**Comment by ryanlarkin** [comment]
What about #15?

**Comment by Patadorea** [comment]
We'll only use this if necessary, people be respectful of Tylar's email, K?

**Comment by ryanlarkin** [comment]
Click unsubscribe

**Comment by ryanlarkin** [comment]
Hello

**Comment by ryanlarkin** [comment]
A test

**Comment by Patadorea** [comment]
Test

**Comment by EAPrado** [comment]
123?

**Comment by EAPrado** [comment]
Everybody dance now!

**Comment by ryanlarkin** [comment]
What do you think about #15?

**Comment by ryanlarkin** [comment]
@D3ZOMBKEELA, what do you think I should work on?

**Comment by ghost** [comment]
You can work on an input interface. I guess? Or maybe a file interface? Idk. You choose.

**Comment by ryanlarkin** [comment]
Like user input handling and loading a config file?

**Comment by ghost** [comment]
Yeah something like that.

**Comment by ryanlarkin** [comment]
Ok

**Comment by MatEdwards** [comment]
No longer part of organisation ;__; but can still contribute

**Comment by MatEdwards** [comment]
Username: MntnDeww
Password: ***********

**Comment by Patadorea** [comment]
Tylar, are you online?

**Comment by Patadorea** [comment]
Ryan wants to merge his recent changes so we can both work on it, could you merge it for us?

**Comment by ryanlarkin** [comment]
Closing dead issue.
