### ISSUE TITLE
Make Window Re-sizable and Maximisable

### ISSUE THREAD

**Issue by ryanlarkin** [AstechzGO/Luminescent#15]

**Comment by ryanlarkin** [comment]
Another test

**Comment by Patadorea** [comment]
Look in #8  At my list.

**Comment by ryanlarkin** [comment]
@Patadorea says that it is better in fullscreen

**Comment by ryanlarkin** [comment]
@Patadorea actually says yes.

**Comment by ghost** [comment]
I have two monitors so I think if you just leave it as non-fullscreen to start with that would be great thanks.

**Comment by Patadorea** [comment]
Were leaving it as it is but were going to make it changeable.  Fore some reason Ryan thought I said to not include Window Size modification, I think it's fine. Sorry Tylar for spamming you'r email, would you like me to send you the logos when there done or commit them? You can add me on skype as well if you'd like to talk to me in a non e-mail spamming way.  Patadorea is my username. Bye

**Comment by ryanlarkin** [comment]
I'll do some multi monitor testing

**Comment by ghost** [comment]
Ok. I've almost got an openGL class ready to use that'll just initialize openGL and allow rendering to happen at all.

**Comment by ryanlarkin** [comment]
So it is currently the same as Minecraft fullscreen

**Comment by ghost** [comment]
?

**Comment by ryanlarkin** [comment]
It acts exactly the same as if you went into fullscreen in minecraft

**Comment by ghost** [comment]
Oh. Ok.Can you try to get maximizing working please. It's really annoying not being able to do that.

**Comment by ryanlarkin** [comment]
I haven't found mush on the internet

**Comment by ghost** [comment]
I found a way to do it but it'll take a while to do and would involve changing the structure of the DisplayUtils class and I don't have time to code that right now. I'll see if I can do it tomorrow

**Comment by ryanlarkin** [comment]
Can you send me a link?

**Comment by ghost** [comment]
http://stackoverflow.com/questions/26769496/how-can-i-set-an-opengl-display-window-created-by-opengl-to-maximized
It's the top answer but to make it work with what we have it would involve a bit more overhead, such as setting the title of the JFrame instead of the display.

**Comment by ryanlarkin** [comment]
Well I know that Minecraft doesn't do that.  I still don't know how they do it hought

**Comment by ghost** [comment]
Probably some voodoo magic

**Comment by ghost** [comment]
I'm headed off to bed so night

**Comment by ryanlarkin** [comment]
You're probably right:
http://www.badlogicgames.com/forum/viewtopic.php?t=13071&p=75500

**Comment by ryanlarkin** [comment]
Actually making it start in windowed fixes it temporarily

**Comment by ryanlarkin** [comment]
It is unable to be resized when the displaymode was changed

**Comment by ghost** [comment]
Ok

**Comment by ryanlarkin** [comment]
This won't be necessary.

**Comment by ryanlarkin** [comment]
It sometimes works and sometimes doesn't for Minecraft, not sure why.

**Comment by ryanlarkin** [comment]
You can choose between fullscreen and 848 x 477 or something similar.  So this will be closed.
