### ISSUE TITLE
Some Textures Mess Up Other Stuff

### ISSUE THREAD

**Issue by ryanlarkin** [AstechzGO/Luminescent#41]
These are two screenshots with the same code but different images.

Image number 1 (Working)
![2015-03-02_19 21 09](https://cloud.githubusercontent.com/assets/5788397/6454156/5c785128-c114-11e4-8a10-d126e0bdab8e.png)

Image number 2 (Not Working)
![2015-03-02_19 20 06](https://cloud.githubusercontent.com/assets/5788397/6454165/67a41d84-c114-11e4-9f2b-9e301148c1dc.png)

:

**Comment by ryanlarkin** [comment]
Notice the border difference.

**Comment by ryanlarkin** [comment]
Could have something to do with the compression level

**Comment by ghost** [comment]
I'll look into it

**Comment by ryanlarkin** [comment]
Ok thanks

**Comment by ryanlarkin** [comment]
Possibly fixed by #42

**Comment by ryanlarkin** [comment]
No, now it's worse for both.
![2015-03-02_20 20 09](https://cloud.githubusercontent.com/assets/5788397/6454690/9255bd80-c119-11e4-8ced-db1803187ed5.png)
![2015-03-02_20 18 48](https://cloud.githubusercontent.com/assets/5788397/6454692/93b3c87a-c119-11e4-9e48-5f2f8fc80c82.png)

**Comment by ghost** [comment]
Ok where is the code that renders the image cuz I ran it on my computer and
nothing was rendering at all

**Comment by ryanlarkin** [comment]
Luminescent class:
public static Texture texture;
in try in init: texture = new Texture("icon_128x128", "icons", true);
in tick after border rendering: RenderingUtils.RenderQuad(SCREEN_WIDTH / 2, SCREEN_HEIGHT / 2, texture);

**Comment by ghost** [comment]
Ok thanks

**Comment by ryanlarkin** [comment]
your welcome

**Comment by ryanlarkin** [comment]
Here's the other image I tried:
![face](https://cloud.githubusercontent.com/assets/5788397/6454778/67701a7e-c11a-11e4-80e6-cc58d7a9b5ae.png)

**Comment by ghost** [comment]
Ok thanks

**Comment by ryanlarkin** [comment]
What I can see the face in the border

**Comment by ghost** [comment]
Lol. That's code for you

**Comment by ryanlarkin** [comment]
got it

**Comment by ryanlarkin** [comment]
Fixed by #44
