### ISSUE TITLE
Make Game More Cross Platform

### ISSUE THREAD

**Issue by ryanlarkin** [AstechzGO/Luminescent#7]
I would like to add the natives for all supported LWJGL platforms, and possibly load them in code.

**Comment by ghost** [comment]
Sure thing. I'll add the natives and you can feel free to code them in.

**Comment by ryanlarkin** [comment]
I noticed that FreeBSD and OpenBSD don't have any natives.

**Comment by ghost** [comment]
Do you have any VM arguments set?

**Comment by ghost** [comment]
It won't run for me. It's saying there's a problem finding the lwjgl64 or something

**Comment by ryanlarkin** [comment]
I will work on this in the future.  It is annoying me.

**Comment by ghost** [comment]
You have the problem too?
Or just that you can't add the natives?

**Comment by ryanlarkin** [comment]
Did you change anything?

**Comment by ghost** [comment]
No I didn't change a thing.

**Comment by ryanlarkin** [comment]
is your natives folder natives/windows or natives/Windows?

**Comment by Patadorea** [comment]
Rawr, Freaking paint. Why u make me hate.

**Comment by ghost** [comment]
That fixed it -_-. Thanks Ryan

**Comment by ryanlarkin** [comment]
Then why is it lowercase on github?

**Comment by ghost** [comment]
No it wasn't lowercase so it didn't work, when I changed it to lowercase it did work.

**Comment by Patadorea** [comment]
Why do you guys have Window or windows files.  You two need to commit or we wont have updated stuff to work on. Anyways,if you did that the windows files  would have been consistent.

**Comment by ghost** [comment]
I think that github just ignores whether they are lower case or upper case so it didn't change it but eclipse notices a difference so it had problems with it.

**Comment by Patadorea** [comment]
I don't have a windows file and I just pulled. Can one of you commit so I can see where we are. I won't be able to finish the logos until tomorrow night so I just gave Ryan some fillers. (Beautiful I know)

**Comment by ghost** [comment]
It should be a windows folder not a file, and what fillers?

**Comment by Patadorea** [comment]
Just some image icons i made, there pngs but have a beautiful face of : I
And yeah, folder not file. Not showing up :/ 
When did you guys add the windows file?

**Comment by Patadorea** [comment]
Wait nvm, I did a refresh and they showed up : P

**Comment by ghost** [comment]
Ok good.

**Comment by Patadorea** [comment]
I made an organizational change that Ryan wants to commit from my computer but I can't add it to the index. Help?

**Comment by MatEdwards** [comment]
hallo

**Comment by ghost** [comment]
Can Ryan help you with that?

**Comment by Patadorea** [comment]
He had a rage and left so no. He's now distracted. Lol, it's ok though, let me see what I can do.

**Comment by Patadorea** [comment]
Ok, Tylar.  We have to come up with a list of needs and wants.

**Comment by Patadorea** [comment]
So far we have a full screen toggle with F11, we have a close with esc and we have logo images being loaded as we speak.
OK, let's start a new Issue and get everyone in on it.

**Comment by MatEdwards** [comment]
... JRE System Library [JavaSE-1.8] has decided to be unbound ;___;

**Comment by MatEdwards** [comment]
i have tried installing JRE 8 but did nothing

**Comment by ghost** [comment]
Ok there is a new issue for wants and needs

**Comment by MatEdwards** [comment]
ok
