### ISSUE TITLE
At 0 Degrees and 180 Degrees on the pacman it shifts 45 Degrees

### ISSUE THREAD

**Issue by cnnradams** [AstechzGO/Luminescent#82]

**Comment by ryanlarkin** [comment]
It may have something to do with the slopes being close to infinite degrees.

**Comment by ryanlarkin** [comment]
And can you provide a description and a GIF or video showing the problem?

**Comment by ryanlarkin** [comment]
Also, I'll aim to fix this for 0.2

**Comment by ryanlarkin** [comment]
Fixed in #88
