### ISSUE TITLE
Rotating is broken on my laptop

### ISSUE THREAD

**Issue by cnnradams** [AstechzGO/Luminescent#94]
It stays between the 90 and 180 angle, and it does not follow the mouse at full speed

**Comment by ryanlarkin** [comment]
I assume you are using the latest code?

**Comment by ryanlarkin** [comment]
Are you in fullscreen?

**Comment by cnnradams** [comment]
The latest code in major-update yes

**Comment by cnnradams** [comment]
I'll show you at robotics if you want

**Comment by cnnradams** [comment]
No wasnt

**Comment by ryanlarkin** [comment]
Do you have multiple monitors connected?

**Comment by ryanlarkin** [comment]
I won't be at robotics tonight but I think I'll be there tomorrow.

**Comment by ryanlarkin** [comment]
For now, I'll set this to "can't reproduce". Also, what's your screen resolution, and why did you create the bugfix branch?

**Comment by ryanlarkin** [comment]
Actually, I got the bug by changing my resolution.

**Comment by ryanlarkin** [comment]
Here's the broken code:

```
x = x + xpos.get(0) + ((Camera.CAMERA_WIDTH / 2) - xpos.get(0) - DisplayUtils.getDisplayWidth() / 2);
y = -y + DisplayUtils.monitorHeight - ypos.get(0) - ((Camera.CAMERA_HEIGHT / 2) - ypos.get(0) - DisplayUtils.getDisplayHeight() / 2);
```

**Comment by ryanlarkin** [comment]
I used Camera.CAMERA_WIDTH/HEIGHT instead of monitorWidth/Height. Committing fix now.

**Comment by ryanlarkin** [comment]
Could you please test the changes, and close if the fix works?

**Comment by ryanlarkin** [comment]
@Stealth2994, I assume this is fixed, closing.
